<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employment Status_inlineRadioOptions</name>
   <tag></tag>
   <elementGuidId>9f47f91d-205e-4cf6-b893-9eaf94ae29bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inlineRadio1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inlineRadio1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>719300b8-5892-4469-b80f-d86e1d77daac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7f1acab7-9a83-47f9-8fc9-3e755b200b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inlineRadio1</value>
      <webElementGuid>76f62ced-0f9c-40a1-b0ee-1ca3e3c2baa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inlineRadioOptions</value>
      <webElementGuid>e8768ef1-c64f-4de1-ac3c-d916b2e2f3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0ca27f88-53ef-48ae-92f6-11c9983d9244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>option1</value>
      <webElementGuid>4a1bba95-80a0-4831-945f-f8041dcf3000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inlineRadio1&quot;)</value>
      <webElementGuid>6b55a8b0-cecd-4388-99fc-e4f393ddd5bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inlineRadio1']</value>
      <webElementGuid>325c4ca6-f1ea-4823-943a-87ef854fcfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>90c04ba1-3dc5-4aa7-b8c0-96d782851970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inlineRadio1' and @name = 'inlineRadioOptions' and @type = 'radio']</value>
      <webElementGuid>1fd0fbd3-6f67-463e-be70-ed963212ffbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
