<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_exampleCheck1</name>
   <tag></tag>
   <elementGuidId>1cfc46b2-c02f-43b1-9848-cb4a2cddb1d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleCheck1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleCheck1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fba196be-9009-4945-8c79-2162b01bc1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d55ece2a-6f9a-4890-b8c2-9cca93525752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleCheck1</value>
      <webElementGuid>7987e9cd-96d5-48cd-b200-a623c01da938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>52e6a44c-f181-4f27-a362-1cfd79e10a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleCheck1&quot;)</value>
      <webElementGuid>f5c91a45-b084-45d2-9224-fe30f3286ebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleCheck1']</value>
      <webElementGuid>83a74b7b-1d41-46bb-88d4-bb0b8333159b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>67e187e3-7064-44e8-9000-c362fd1df146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'exampleCheck1' and @type = 'checkbox']</value>
      <webElementGuid>89880bb3-f32a-4e20-97f7-d22be15e3ec7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
