<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Male                        Female</name>
   <tag></tag>
   <elementGuidId>56d50419-8a17-4188-9576-e19b9ccd1d53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleFormControlSelect1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='exampleFormControlSelect1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>39ba58a2-0fbe-4b5d-9367-d0aa99163fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>76f84efd-0af3-42c3-9537-122714d9cacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleFormControlSelect1</value>
      <webElementGuid>ed6e999e-115a-4604-b5b6-a1f03edd95c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Male
                        Female
                      </value>
      <webElementGuid>e19a1d4c-a9ae-4ce4-a863-3aa24dbd12f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleFormControlSelect1&quot;)</value>
      <webElementGuid>99a678e0-7145-42c5-9019-bdedad6b2609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='exampleFormControlSelect1']</value>
      <webElementGuid>a04481f9-cd2d-470d-a2d4-289daae2a632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::select[1]</value>
      <webElementGuid>371c0d6c-4dcb-4968-804e-0f60ea37f05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Check me out if you Love IceCreams!'])[1]/following::select[1]</value>
      <webElementGuid>f75f970d-0efe-4ecd-a5be-68fa93b2c52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employment Status:'])[1]/preceding::select[1]</value>
      <webElementGuid>0e339e10-df06-421c-be2f-e44aa471d76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Student'])[1]/preceding::select[1]</value>
      <webElementGuid>e414789d-e7a0-4a61-868b-9ae6f881c5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>988196d3-5036-43d3-bdfc-2c8559eb6372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'exampleFormControlSelect1' and (text() = '
                        Male
                        Female
                      ' or . = '
                        Male
                        Female
                      ')]</value>
      <webElementGuid>353d0425-65a9-42a4-81b5-babbfe5c167c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
